apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daily-art-of-war-quote
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhefner/daily-art-of-war-quote
    targetRevision: HEAD
    path: overlay/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
